-- NOTE: This file is auto generated by ./sql-generator

-- StorageTargetRepository.getAll
select
  "storage_target".*
from
  "storage_target"
order by
  "name" asc

-- StorageTargetRepository.get
select
  "storage_target".*
from
  "storage_target"
where
  "id" = $1

-- StorageTargetRepository.getByName
select
  "storage_target".*
from
  "storage_target"
where
  "name" = $1

-- StorageTargetRepository.getTransfer
select
  "storage_target_transfer".*
from
  "storage_target_transfer"
where
  "id" = $1

-- StorageTargetRepository.getTransfers
select
  "storage_target_transfer".*
from
  "storage_target_transfer"
where
  "targetId" = $1
order by
  "createdAt" desc
limit
  $2

-- StorageTargetRepository.streamAssetsForExport
select
  "asset"."id"
from
  "asset"
where
  "asset"."ownerId" = $1
  and "asset"."deletedAt" is null
  and "asset"."isExternal" = $2
  and "asset"."isOffline" = $3
  and "asset"."visibility" != $4

-- StorageTargetRepository.streamAssetsForOffload
select
  "asset"."id"
from
  "asset"
where
  "asset"."ownerId" = $1
  and "asset"."deletedAt" is null
  and "asset"."isExternal" = $2
  and "asset"."isOffline" = $3
  and "asset"."visibility" != $4
  and "asset"."offloadedAt" is null
  and exists (
    select
      "asset_file"."id"
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = $5
  )
  and exists (
    select
      "asset_file"."id"
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = $6
  )

-- StorageTargetRepository.countAssetsMissingPreviews
select
  count(*) as "count"
from
  (
    select
      "asset"."id"
    from
      "asset"
    where
      "asset"."ownerId" = $1
      and "asset"."deletedAt" is null
      and "asset"."isExternal" = $2
      and "asset"."isOffline" = $3
      and "asset"."visibility" != $4
      and "asset"."offloadedAt" is null
      and (
        not exists (
          select
            "asset_file"."id"
          from
            "asset_file"
          where
            "asset_file"."assetId" = "asset"."id"
            and "asset_file"."type" = $5
        )
        or not exists (
          select
            "asset_file"."id"
          from
            "asset_file"
          where
            "asset_file"."assetId" = "asset"."id"
            and "asset_file"."type" = $6
        )
      )
  ) as "candidate"

-- StorageTargetRepository.streamAssetsForRestore
select
  "asset"."id"
from
  "asset"
where
  "asset"."ownerId" = $1
  and "asset"."deletedAt" is null
  and "asset"."offloadedAt" is not null

-- StorageTargetRepository.getAssetForExport
select
  "asset"."id",
  "asset"."ownerId",
  "asset"."originalPath",
  "asset"."originalFileName",
  "asset"."checksum",
  "asset"."type",
  "asset"."offloadedAt",
  "asset_exif"."fileSizeInByte"
from
  "asset"
  left join "asset_exif" on "asset"."id" = "asset_exif"."assetId"
where
  "asset"."id" = $1

-- StorageTargetRepository.getOffloadLocation
select
  "storage_target"."id",
  "storage_target"."updatedAt",
  "storage_target"."config",
  "storage_target"."secret",
  "storage_target"."name",
  "storage_target_object"."remoteKey",
  "storage_target_object"."size"
from
  "storage_target_object"
  inner join "storage_target" on "storage_target"."id" = "storage_target_object"."targetId"
where
  "storage_target_object"."assetId" = $1
  and "storage_target"."isEnabled" = $2
order by
  "storage_target_object"."syncedAt" desc

-- StorageTargetRepository.countOffloadedAssets
select
  count(*) as "count"
from
  "storage_target_object"
  inner join "asset" on "asset"."id" = "storage_target_object"."assetId"
where
  "storage_target_object"."targetId" = $1
  and "asset"."offloadedAt" is not null

-- StorageTargetRepository.getObjectByAsset
select
  "storage_target_object".*
from
  "storage_target_object"
where
  "targetId" = $1
  and "assetId" = $2

-- StorageTargetRepository.filterNewRemoteKeys
select
  "remoteKey"
from
  "storage_target_object"
where
  "targetId" = $1
  and "remoteKey" in ($2)
